# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/BowlingKata.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1


- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

# Preparation of sonar MUST be before build task. 
# More info: https://docs.sonarqube.org/latest/analysis/scan/sonarscanner-for-azure-devops/
- task: SonarQubePrepare@4
  inputs:
    SonarQube: 'SonarqubeInMyAzure'
    scannerMode: 'MSBuild'
    projectKey: 'SonarAzureDevOps' # This literals are in the configuration of the sonar project
    projectName: 'SonarAzureDevOps'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:DeployOnBuild=false /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  inputs:
    testSelector: 'testAssemblies'
    testAssemblyVer2: |
      **\*BownlingCode.Test.dll
      !**\obj\**
    searchFolder: '$(System.DefaultWorkingDirectory)'

# MBA: This task works fine and publish test results, but it's redundant
# because VSTest@2 publish the test results when it's executed
# - task: PublishTestResults@2
#   inputs:
#     testResultsFormat: 'VSTest'
#     testResultsFiles: '**/*.trx'
#     failTaskOnFailedTests: true
#     searchFolder: '$(Agent.TempDirectory)'
#     testRunTitle: 'Testing bowling'


# Execution of sonar analysisMUST be after test execution. 
# More info: https://docs.sonarqube.org/latest/analysis/scan/sonarscanner-for-azure-devops/
- task: SonarQubeAnalyze@4
- task: SonarQubePublish@4
  inputs:
    pollingTimeoutSec: '300'

 #  --> Prepare Analysis Configuration task before any MSBuild or Visual Studio Build tasks.
 #  --> Run Code Analysis task after the Visual Studio Test task.
 #  --> Publish Quality Gate Result task after the Run Code Analysis task